//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class TabSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TabSettings defaultInstance = ((TabSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TabSettings())));
        
        public static TabSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
